config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  resources :dinosaurs do
    resources :comments, only: [:new, :create]
    collection do
      get :carnivorous
      get :herbivorous
      # get "carnivorous", to: "dinosaurs#carnivorous", as: :carnivorous_dinosaurs
    end
  end
  resources :comments, only: [:destroy]
end

# get 'dinosaurs', to: 'dinosaurs#index'
# get 'dinosaurs/new', to: 'dinosaurs#new'
# get 'dinosaurs/:id', to: 'dinosaurs#show', as: :dinosaur
# post 'dinosaurs', to: 'dinosaurs#create'
# get 'dinosaurs/:id/edit', to: 'dinosaurs#edit'
# patch 'dinosaurs/:id', to: 'dinosaurs#update'
# delete 'dinosaurs/:id', to: 'dinosaurs#destroy'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :dinosaur
  # allows us to do: @comment.dinosaur
  validates :content, presence: true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  has_many :comments, dependent: :destroy
  attribute :image, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_dinosaur, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.dinosaur = @dinosaur
    if @comment.save
      redirect_to dinosaur_path(@dinosaur)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to dinosaur_path(@comment.dinosaur), status: :see_other
  end
  private

  def set_dinosaur
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  before_action :set_dinosaur, only: [:show, :edit, :update, :destroy]
  def index
    @dinosaurs = Dinosaur.all
  end

  def carnivorous
    @dinosaurs = Dinosaur.where(group: 'carnivorous')
  end

  def herbivorous
    @dinosaurs = Dinosaur.where(group: 'herbivorous')
  end

  def show
  end

  def new
    @dinosaur = Dinosaur.new
  end

  def create
    @dinosaur = Dinosaur.new(dinosaur_params)
    @dinosaur.save
    redirect_to dinosaur_path(@dinosaur)
  end

  def edit
  end

  def update
    @dinosaur.update(dinosaur_params)
    redirect_to dinosaur_path(@dinosaur)
  end

  def destroy
    @dinosaur.destroy
    redirect_to dinosaurs_path, status: :see_other
  end
end

private

def set_dinosaur
  @dinosaur = Dinosaur.find(params[:id])
end

def dinosaur_params
  params.require(:dinosaur).permit(:name, :group, :japanese, :image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/comments/new.html.erb
<h1>New comment</h1>
<%= simple_form_for [@dinosaur, @comment] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit comment", class: "btn btn-primary" %>
<% end %>

app/views/dinosaurs/_form.html.erb
<%= form_with model: dinosaur do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :group %>
  <%= f.text_field :group %>
  <%= f.label :japanese %>
  <%= f.text_field :japanese %>
  <%# <%= f.label :image %>
  <%# <%= f.text_field :image %>
  <%= f.submit %>
<% end %>

app/views/dinosaurs/carnivorous.html.erb
<div class="container">
  <h1> 🥩 Carnivorous Dinosaurs 🥩 </h1>
  <div id="dinosaurs">
    <% @dinosaurs.each do |dinosaur| %>
      <p>
        <strong>Name:</strong> <%= dinosaur.name.capitalize %>
      </p>
      <p>
        <strong>Group:</strong> <%= dinosaur.group.capitalize %>
      </p>
      <p>
        <strong>Japanese:</strong> <%= dinosaur.japanese %>
      </p>
      <p>
        <%= link_to "Show this 🥩🦖", dinosaur %>
      </p>
      <hr>
    <% end %>
  </div>
</div>

app/views/dinosaurs/edit.html.erb
<h1>Edit <%= Dinosaur.name %></h1>
<%= render "form", dinosaur: @dinosaur %>

app/views/dinosaurs/herbivorous.html.erb
<div class="container">
  <h1> 🌿 Herbivorous Dinosaurs 🌿 </h1>
  <div id="dinosaurs">
    <% @dinosaurs.each do |dinosaur| %>
      <p>
        <strong>Name:</strong> <%= dinosaur.name.capitalize %>
      </p>
      <p>
        <strong>Group:</strong> <%= dinosaur.group.capitalize %>
      </p>
      <p>
        <strong>Japanese:</strong> <%= dinosaur.japanese %>
      </p>
      <p>
        <%= link_to "Show this 🌿🦕", dinosaur %>
      </p>
      <hr>
    <% end %>
  </div>
</div>

app/views/dinosaurs/index.html.erb
<div class="container">
  <%# Banner %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://djm-aaa1.kxcdn.com/resources/upload/products/71XDgIw333L._AC_SL1000_.jpg);">
    <div class="container">
      <h1>Dinocrud <strong>for all</strong> who <strong>loves dinosaurs</strong>!</h1>
      <p>Change your life and love dinosaurs</p>
      <a class="btn btn-flat" href= <%= new_dinosaur_path %> >Add a Dinosaur</a>
    </div>
  </div>
  <%# Banner end %>
  <p style="color: green"><%= notice %></p>
  <p> 🗯️ Rrrrrrrrrrrrrrrrrr 🗯️ </p>
  <%# <p><%= link_to "Carnivorous Dinosaurs 🥩🦖", carnivorous_dinosaurs_path %></p>
<%# <p><%= link_to "Herbivorous Dinosaurs 🌿🦕", herbivorous_dinosaurs_path %></p>
<hr>
<%# <ul>
  <% @dinosaurs.each do |dinosaur| %>
  <%# <li><%= link_to dinosaur.name.capitalize, dinosaur_path(dinosaur) %></li>
<%# <%end %>
<%# </ul> %>
<%# <%= link_to "New", new_dinosaur_path %>
<%# Test  %>
<div class="cards">
  <% @dinosaurs.each do |dinosaur| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dinosaur.image ? (dinosaur.image) : 'https://djm-aaa1.kxcdn.com/resources/upload/products/71XDgIw333L._AC_SL1000_.jpg' %>)">
      <div class="cards-links">
        <%= link_to dinosaur.name.capitalize, dinosaur_path(dinosaur) %>
      </div>
    </div>
  <%end %>
</div>
</div>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur 🥚</h1>
<%= render "form", dinosaur: @dinosaur %>

app/views/dinosaurs/show.html.erb
<h1><%= @dinosaur.name.capitalize %></h1>
<p>Group: <%= @dinosaur.group.capitalize %></p>
<p>Japanese: <%= @dinosaur.japanese %></p>
<p>Image: <%= @dinosaur.image %> </p>
<i class="fa-solid fa-heart"></i>
<br>
<p><strong>Comments</strong></p>
<%= link_to "Add comment", new_dinosaur_comment_path(@dinosaur)  %>
<ul class="list-group">
  <% @dinosaur.comments.each do |comment| %>
    <li class="list-group-item">
      <%= comment.content %>
      <%= link_to "Delete", comment_path(comment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
    </li>
  <% end %>
</ul>
<br>
<div>
  <%= link_to "Back to Dinosaurs", dinosaurs_path %> |
  <%= link_to "Edit this Dinosaur", edit_dinosaur_path(@dinosaur) %> |
  <%= link_to "Delete this Dinosaur", dinosaur_path(@dinosaur), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinocrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%# Navbar %>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon", mb-3 >
      <div class="container-fluid">
        <%= link_to dinosaurs_path, class: "navbar-brand" do %>
          <%= image_tag "dinosaur-logo.svg", alt: "Dino 8 bit logo", width: 50 %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <%# if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Carnivorous 🥩🦖", carnivorous_dinosaurs_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Herbivorous 🌿🦕", herbivorous_dinosaurs_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "Tyrannosaurus avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
            <%# else %>
            <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
            <!--/li-->
            <%# end %>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
    <%# Footer %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> by Julien
      </div>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>